spring.application.name=isa.yt
spring.datasource.url=jdbc:postgresql://localhost:5432/jpa
spring.datasource.username=postgres
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybuns.noreply60@gmail.com
spring.mail.password=tbry eftl mats vhdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true

resilience4j.ratelimiter.instances.standard.limitForPeriod=5
resilience4j.ratelimiter.instances.standard.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.standard.timeoutDuration=0s